import type { User, UserPayload } from "@/app/types/user";
import type {AuthDomain, AuthSession} from "@/app/types/auth";
import { Menu } from "../types/auth";

type AuthPayload = {
  username: string;
  password: string;
  domain: AuthDomain;
};

const now = () => new Date().toISOString();

let users: User[] = [
  {
    id: "U-1001",
    firstName: "Ava",
    lastName: "Nguyen",
    email: "ava.nguyen@example.com",
    phone: "+66 81 234 5678",
    role: "admin",
    status: "active",
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "U-1002",
    firstName: "Somchai",
    lastName: "Prasert",
    email: "somchai.prasert@example.com",
    phone: "+66 89 555 2121",
    role: "sale",
    status: "inactive",
    createdAt: now(),
    updatedAt: now(),
  },
];
let menu: Menu[] = [
 {
   "TABLENAME": "M_MENU",
   "ID": 1,
   "MENU_NAME": "ราคา LNG",
   "MENU_URL": "~",
   "MENU_LEVEL": 1,
   "PARENT_MENU_ID": null,
   "DESCRIPTION": "",
   "ROW_ORDER": 1,
   "IS_ACTIVE": 1,
   "CREATE_BY": 1,
   "CREATE_DATETIME": "6/28/2018 1:53:01 PM",
   "UPDATE_BY": 1,
   "UPDATE_DATETIME": "6/28/2018 1:53:03 PM",
   "ACTIVEMAIN": "LNG",
   "ACTIVE": "",
   "MENU_ICON": "fa fa-dashboard",
   "MENU_ID": 1
 },
 {
   "TABLENAME": "M_MENU",
   "ID": 6,
   "MENU_NAME": "ราคา LNG ย้อนหลัง",
   "MENU_URL": "~/PriceHistory",
   "MENU_LEVEL": 1,
   "PARENT_MENU_ID": null,
   "DESCRIPTION": "",
   "ROW_ORDER": 2,
   "IS_ACTIVE": 1,
   "CREATE_BY": 1,
   "CREATE_DATETIME": "6/28/2018 2:21:22 PM",
   "UPDATE_BY": 1,
   "UPDATE_DATETIME": "6/28/2018 2:21:24 PM",
   "ACTIVEMAIN": "PriceHistory",
   "ACTIVE": "",
   "MENU_ICON": "fa fa-area-chart",
   "MENU_ID": 6
 },
 {
   "TABLENAME": "M_MENU",
   "ID": 41,
   "MENU_NAME": "Sale Report",
   "MENU_URL": "~/SaleReport",
   "MENU_LEVEL": 1,
   "PARENT_MENU_ID": null,
   "DESCRIPTION": "",
   "ROW_ORDER": 3,
   "IS_ACTIVE": 1,
   "CREATE_BY": 1,
   "CREATE_DATETIME": "6/15/2021 4:22:51 PM",
   "UPDATE_BY": null,
   "UPDATE_DATETIME": "",
   "ACTIVEMAIN": "SaleReport",
   "ACTIVE": "",
   "MENU_ICON": "fa fa-bar-chart",
   "MENU_ID": 41
 },
 {
   "TABLENAME": "M_MENU",
   "ID": 42,
   "MENU_NAME": "Plan Volume",
   "MENU_URL": "~/PlanVolume",
   "MENU_LEVEL": 1,
   "PARENT_MENU_ID": null,
   "DESCRIPTION": "",
   "ROW_ORDER": 4,
   "IS_ACTIVE": 1,
   "CREATE_BY": 1,
   "CREATE_DATETIME": "6/15/2021 4:22:51 PM",
   "UPDATE_BY": 1,
   "UPDATE_DATETIME": "",
   "ACTIVEMAIN": "PlanVolume",
   "ACTIVE": "",
   "MENU_ICON": "fa fa-tint",
   "MENU_ID": 42
 },
 {
   "TABLENAME": "M_MENU",
   "ID": 43,
   "MENU_NAME": "Document",
   "MENU_URL": "~/Document",
   "MENU_LEVEL": 1,
   "PARENT_MENU_ID": null,
   "DESCRIPTION": "",
   "ROW_ORDER": 5,
   "IS_ACTIVE": 1,
   "CREATE_BY": 1,
   "CREATE_DATETIME": "6/15/2021 4:22:51 PM",
   "UPDATE_BY": 1,
   "UPDATE_DATETIME": "",
   "ACTIVEMAIN": "Document",
   "ACTIVE": "",
   "MENU_ICON": "fa fa-file-o",
   "MENU_ID": 43
 },
 {
   "TABLENAME": "M_MENU",
   "ID": 2,
   "MENU_NAME": "Transaction",
   "MENU_URL": "",
   "MENU_LEVEL": 1,
   "PARENT_MENU_ID": null,
   "DESCRIPTION": "",
   "ROW_ORDER": 12,
   "IS_ACTIVE": 1,
   "CREATE_BY": 1,
   "CREATE_DATETIME": "6/28/2018 1:54:43 PM",
   "UPDATE_BY": 1,
   "UPDATE_DATETIME": "6/28/2018 1:54:45 PM",
   "ACTIVEMAIN": "Transaction",
   "ACTIVE": "",
   "MENU_ICON": "fa fa-desktop",
   "MENU_ID": 2
 },
 {
   "TABLENAME": "M_MENU",
   "ID": 11,
   "MENU_NAME": "System",
   "MENU_URL": "",
   "MENU_LEVEL": 1,
   "PARENT_MENU_ID": null,
   "DESCRIPTION": "",
   "ROW_ORDER": 13,
   "IS_ACTIVE": 1,
   "CREATE_BY": 1,
   "CREATE_DATETIME": "11/4/2019 3:52:24 PM",
   "UPDATE_BY": 1,
   "UPDATE_DATETIME": "11/4/2019 3:52:24 PM",
   "ACTIVEMAIN": "System",
   "ACTIVE": "",
   "MENU_ICON": "fa   fa-cogs",
   "MENU_ID": 11
 },
 {
   "TABLENAME": "M_MENU",
   "ID": 3,
   "MENU_NAME": "Master",
   "MENU_URL": "",
   "MENU_LEVEL": 1,
   "PARENT_MENU_ID": null,
   "DESCRIPTION": "",
   "ROW_ORDER": 13,
   "IS_ACTIVE": 1,
   "CREATE_BY": 1,
   "CREATE_DATETIME": "6/28/2018 1:55:31 PM",
   "UPDATE_BY": 1,
   "UPDATE_DATETIME": "6/28/2018 1:55:32 PM",
   "ACTIVEMAIN": "Master",
   "ACTIVE": "",
   "MENU_ICON": "fa fa-cogs",
   "MENU_ID": 3
 },
 {
   "TABLENAME": "M_MENU",
   "ID": 48,
   "MENU_NAME": "บันทึกราคา CT",
   "MENU_URL": "~/PriceCT",
   "MENU_LEVEL": 2,
   "PARENT_MENU_ID": 2,
   "DESCRIPTION": "",
   "ROW_ORDER": 1,
   "IS_ACTIVE": 1,
   "CREATE_BY": 1,
   "CREATE_DATETIME": "11/28/2022 2:29:39 PM",
   "UPDATE_BY": 1,
   "UPDATE_DATETIME": "11/28/2022 2:29:39 PM",
   "ACTIVEMAIN": "Transaction",
   "ACTIVE": "PriceCT",
   "MENU_ICON": "",
   "MENU_ID": 48
 },
 {
   "TABLENAME": "M_MENU",
   "ID": 4,
   "MENU_NAME": "Upload ราคา LNG",
   "MENU_URL": "~/UploadPrice",
   "MENU_LEVEL": 2,
   "PARENT_MENU_ID": 2,
   "DESCRIPTION": "",
   "ROW_ORDER": 1,
   "IS_ACTIVE": 1,
   "CREATE_BY": 1,
   "CREATE_DATETIME": "6/28/2018 2:19:41 PM",
   "UPDATE_BY": 1,
   "UPDATE_DATETIME": "6/28/2018 2:19:42 PM",
   "ACTIVEMAIN": "Transaction",
   "ACTIVE": "UploadPrice",
   "MENU_ICON": "",
   "MENU_ID": 4
 },
 {
   "TABLENAME": "M_MENU",
   "ID": 5,
   "MENU_NAME": "อนุมัติราคา LNG",
   "MENU_URL": "~/PriceApprove",
   "MENU_LEVEL": 2,
   "PARENT_MENU_ID": 2,
   "DESCRIPTION": "",
   "ROW_ORDER": 2,
   "IS_ACTIVE": 1,
   "CREATE_BY": 1,
   "CREATE_DATETIME": "6/28/2018 2:20:15 PM",
   "UPDATE_BY": 1,
   "UPDATE_DATETIME": "6/28/2018 2:20:17 PM",
   "ACTIVEMAIN": "Transaction",
   "ACTIVE": "PriceApprove",
   "MENU_ICON": "",
   "MENU_ID": 5
 },
 {
   "TABLENAME": "M_MENU",
   "ID": 25,
   "MENU_NAME": "Create Billing From PTT LNG",
   "MENU_URL": "~/CreateBillingFromPTTLNG",
   "MENU_LEVEL": 2,
   "PARENT_MENU_ID": 2,
   "DESCRIPTION": "",
   "ROW_ORDER": 12,
   "IS_ACTIVE": 1,
   "CREATE_BY": 1,
   "CREATE_DATETIME": "3/23/2020 2:41:51 PM",
   "UPDATE_BY": 1,
   "UPDATE_DATETIME": "3/23/2020 2:41:51 PM",
   "ACTIVEMAIN": "Transaction",
   "ACTIVE": "CreateBillingPTTLNG",
   "MENU_ICON": "",
   "MENU_ID": 25
 },
 {
   "TABLENAME": "M_MENU",
   "ID": 13,
   "MENU_NAME": "Create Billing",
   "MENU_URL": "~/CreateBilling",
   "MENU_LEVEL": 2,
   "PARENT_MENU_ID": 2,
   "DESCRIPTION": "",
   "ROW_ORDER": 13,
   "IS_ACTIVE": 1,
   "CREATE_BY": 1,
   "CREATE_DATETIME": "9/23/2018 4:30:56 PM",
   "UPDATE_BY": 1,
   "UPDATE_DATETIME": "9/24/2018 4:29:19 PM",
   "ACTIVEMAIN": "Transaction",
   "ACTIVE": "CreateBilling",
   "MENU_ICON": "",
   "MENU_ID": 13
 },
 {
   "TABLENAME": "M_MENU",
   "ID": 47,
   "MENU_NAME": "Approve Order",
   "MENU_URL": "~/ApproveOrder",
   "MENU_LEVEL": 2,
   "PARENT_MENU_ID": 2,
   "DESCRIPTION": "",
   "ROW_ORDER": 13,
   "IS_ACTIVE": 1,
   "CREATE_BY": 1,
   "CREATE_DATETIME": "11/27/2018 11:56:17 AM",
   "UPDATE_BY": 1,
   "UPDATE_DATETIME": "11/27/2018 11:56:17 AM",
   "ACTIVEMAIN": "Transaction",
   "ACTIVE": "ApproveOrder",
   "MENU_ICON": "",
   "MENU_ID": 47
 },
 {
   "TABLENAME": "M_MENU",
   "ID": 17,
   "MENU_NAME": "อนุมัติ Invoice",
   "MENU_URL": "~/InvoiceApprove",
   "MENU_LEVEL": 2,
   "PARENT_MENU_ID": 2,
   "DESCRIPTION": "",
   "ROW_ORDER": 14,
   "IS_ACTIVE": 1,
   "CREATE_BY": 1,
   "CREATE_DATETIME": "11/27/2018 11:56:17 AM",
   "UPDATE_BY": 1,
   "UPDATE_DATETIME": "11/27/2018 11:56:17 AM",
   "ACTIVEMAIN": "Transaction",
   "ACTIVE": "InvoiceApprove",
   "MENU_ICON": "",
   "MENU_ID": 17
 },
 {
   "TABLENAME": "M_MENU",
   "ID": 22,
   "MENU_NAME": "Upload ราคา เชื้อเพลิงชนิดอื่น",
   "MENU_URL": "~/UploadFuel",
   "MENU_LEVEL": 2,
   "PARENT_MENU_ID": 2,
   "DESCRIPTION": "",
   "ROW_ORDER": 15,
   "IS_ACTIVE": 1,
   "CREATE_BY": 1,
   "CREATE_DATETIME": "11/4/2019 3:52:24 PM",
   "UPDATE_BY": 1,
   "UPDATE_DATETIME": "11/4/2019 3:52:24 PM",
   "ACTIVEMAIN": "Transaction",
   "ACTIVE": "UploadFuel",
   "MENU_ICON": "",
   "MENU_ID": 22
 },
 {
   "TABLENAME": "M_MENU",
   "ID": 34,
   "MENU_NAME": "Maintain Rebilling ",
   "MENU_URL": "~/MaintainRebilling",
   "MENU_LEVEL": 2,
   "PARENT_MENU_ID": 2,
   "DESCRIPTION": "",
   "ROW_ORDER": 16,
   "IS_ACTIVE": 1,
   "CREATE_BY": 0,
   "CREATE_DATETIME": "11/4/2019 3:52:25 PM",
   "UPDATE_BY": 0,
   "UPDATE_DATETIME": "11/4/2019 3:52:25 PM",
   "ACTIVEMAIN": "Transaction",
   "ACTIVE": "MaintainRebilling",
   "MENU_ICON": "",
   "MENU_ID": 34
 },
 {
   "TABLENAME": "M_MENU",
   "ID": 37,
   "MENU_NAME": "Download Price Sheet",
   "MENU_URL": "~/DownloadPriceSheet",
   "MENU_LEVEL": 2,
   "PARENT_MENU_ID": 2,
   "DESCRIPTION": "",
   "ROW_ORDER": 27,
   "IS_ACTIVE": 1,
   "CREATE_BY": 1,
   "CREATE_DATETIME": "6/25/2020 10:20:10 PM",
   "UPDATE_BY": null,
   "UPDATE_DATETIME": "",
   "ACTIVEMAIN": "Transaction",
   "ACTIVE": "DownloadPriceSheet",
   "MENU_ICON": "",
   "MENU_ID": 37
 },
 {
   "TABLENAME": "M_MENU",
   "ID": 40,
   "MENU_NAME": "ประวัติการอนุมัติราคา LNG",
   "MENU_URL": "~/ViewPriceApprove",
   "MENU_LEVEL": 2,
   "PARENT_MENU_ID": 2,
   "DESCRIPTION": "",
   "ROW_ORDER": 28,
   "IS_ACTIVE": 1,
   "CREATE_BY": 1,
   "CREATE_DATETIME": "6/28/2018 2:20:15 PM",
   "UPDATE_BY": 1,
   "UPDATE_DATETIME": "6/28/2018 2:20:17 PM",
   "ACTIVEMAIN": "Transaction",
   "ACTIVE": "ViewPriceApprove",
   "MENU_ICON": "",
   "MENU_ID": 40
 },
 {
   "TABLENAME": "M_MENU",
   "ID": 38,
   "MENU_NAME": "อนุมัติราคา LNG(ใหม่)",
   "MENU_URL": "~/PriceApproveNew",
   "MENU_LEVEL": 2,
   "PARENT_MENU_ID": 2,
   "DESCRIPTION": "",
   "ROW_ORDER": 28,
   "IS_ACTIVE": 1,
   "CREATE_BY": 1,
   "CREATE_DATETIME": "6/25/2020 10:20:13 PM",
   "UPDATE_BY": 1,
   "UPDATE_DATETIME": "6/25/2020 10:20:13 PM",
   "ACTIVEMAIN": "Transaction",
   "ACTIVE": "PriceApproveNew",
   "MENU_ICON": "",
   "MENU_ID": 38
 },
 {
   "TABLENAME": "M_MENU",
   "ID": 45,
   "MENU_NAME": "TOP / MUR Calculation",
   "MENU_URL": "~/SimulateTopCalculationLog",
   "MENU_LEVEL": 2,
   "PARENT_MENU_ID": 2,
   "DESCRIPTION": "",
   "ROW_ORDER": 29,
   "IS_ACTIVE": 1,
   "CREATE_BY": 1,
   "CREATE_DATETIME": "7/25/2021 12:36:47 PM",
   "UPDATE_BY": null,
   "UPDATE_DATETIME": "",
   "ACTIVEMAIN": "Transaction",
   "ACTIVE": "TopCalculation",
   "MENU_ICON": "",
   "MENU_ID": 45
 },
 {
   "TABLENAME": "M_MENU",
   "ID": 46,
   "MENU_NAME": "Re Billing",
   "MENU_URL": "~/ReBilling",
   "MENU_LEVEL": 2,
   "PARENT_MENU_ID": 2,
   "DESCRIPTION": "",
   "ROW_ORDER": 30,
   "IS_ACTIVE": 1,
   "CREATE_BY": 1,
   "CREATE_DATETIME": "10/30/2021 5:26:44 PM",
   "UPDATE_BY": 1,
   "UPDATE_DATETIME": "",
   "ACTIVEMAIN": "Transaction",
   "ACTIVE": "ReBilling",
   "MENU_ICON": "",
   "MENU_ID": 46
 },
 {
   "TABLENAME": "M_MENU",
   "ID": 49,
   "MENU_NAME": "Supplier",
   "MENU_URL": "~/Supplier",
   "MENU_LEVEL": 2,
   "PARENT_MENU_ID": 3,
   "DESCRIPTION": "",
   "ROW_ORDER": 12,
   "IS_ACTIVE": 1,
   "CREATE_BY": 0,
   "CREATE_DATETIME": "9/24/2018 4:29:19 PM",
   "UPDATE_BY": 0,
   "UPDATE_DATETIME": "9/24/2018 4:29:19 PM",
   "ACTIVEMAIN": "Master",
   "ACTIVE": "Supplier",
   "MENU_ICON": "",
   "MENU_ID": 49
 },
 {
   "TABLENAME": "M_MENU",
   "ID": 14,
   "MENU_NAME": "ลูกค้า",
   "MENU_URL": "~/Customer",
   "MENU_LEVEL": 2,
   "PARENT_MENU_ID": 3,
   "DESCRIPTION": "",
   "ROW_ORDER": 12,
   "IS_ACTIVE": 1,
   "CREATE_BY": 0,
   "CREATE_DATETIME": "9/24/2018 4:29:19 PM",
   "UPDATE_BY": 0,
   "UPDATE_DATETIME": "9/24/2018 4:29:19 PM",
   "ACTIVEMAIN": "Master",
   "ACTIVE": "Customer",
   "MENU_ICON": "",
   "MENU_ID": 14
 },
 {
   "TABLENAME": "M_MENU",
   "ID": 15,
   "MENU_NAME": "Contract/Quotation No",
   "MENU_URL": "~/SaNo",
   "MENU_LEVEL": 2,
   "PARENT_MENU_ID": 3,
   "DESCRIPTION": "",
   "ROW_ORDER": 13,
   "IS_ACTIVE": 1,
   "CREATE_BY": 1,
   "CREATE_DATETIME": "9/28/2018 3:11:35 PM",
   "UPDATE_BY": 1,
   "UPDATE_DATETIME": "9/28/2018 3:11:37 PM",
   "ACTIVEMAIN": "Master",
   "ACTIVE": "SaNo",
   "MENU_ICON": "",
   "MENU_ID": 15
 },
 {
   "TABLENAME": "M_MENU",
   "ID": 33,
   "MENU_NAME": "Bank Guarantee",
   "MENU_URL": "~/BankGuarantee",
   "MENU_LEVEL": 2,
   "PARENT_MENU_ID": 3,
   "DESCRIPTION": "",
   "ROW_ORDER": 20,
   "IS_ACTIVE": 1,
   "CREATE_BY": 0,
   "CREATE_DATETIME": "11/4/2019 3:52:24 PM",
   "UPDATE_BY": 0,
   "UPDATE_DATETIME": "11/4/2019 3:52:24 PM",
   "ACTIVEMAIN": "Master",
   "ACTIVE": "BankGuarantee",
   "MENU_ICON": "",
   "MENU_ID": 33
 },
 {
   "TABLENAME": "M_MENU",
   "ID": 21,
   "MENU_NAME": "เชื้อเพลิงชนิดอื่น",
   "MENU_URL": "~/Fuel",
   "MENU_LEVEL": 2,
   "PARENT_MENU_ID": 3,
   "DESCRIPTION": "",
   "ROW_ORDER": 21,
   "IS_ACTIVE": 1,
   "CREATE_BY": 1,
   "CREATE_DATETIME": "11/4/2019 3:52:24 PM",
   "UPDATE_BY": 1,
   "UPDATE_DATETIME": "",
   "ACTIVEMAIN": "Master",
   "ACTIVE": "Fuel",
   "MENU_ICON": "",
   "MENU_ID": 21
 },
 {
   "TABLENAME": "M_MENU",
   "ID": 24,
   "MENU_NAME": "สกุลเงิน",
   "MENU_URL": "~/Currency",
   "MENU_LEVEL": 2,
   "PARENT_MENU_ID": 3,
   "DESCRIPTION": "",
   "ROW_ORDER": 21,
   "IS_ACTIVE": 1,
   "CREATE_BY": 1,
   "CREATE_DATETIME": "11/4/2019 3:52:24 PM",
   "UPDATE_BY": 1,
   "UPDATE_DATETIME": "11/4/2019 3:52:24 PM",
   "ACTIVEMAIN": "Master",
   "ACTIVE": "Currency",
   "MENU_ICON": "",
   "MENU_ID": 24
 },
 {
   "TABLENAME": "M_MENU",
   "ID": 23,
   "MENU_NAME": "DCQ",
   "MENU_URL": "~/DCQ",
   "MENU_LEVEL": 2,
   "PARENT_MENU_ID": 3,
   "DESCRIPTION": "",
   "ROW_ORDER": 22,
   "IS_ACTIVE": 1,
   "CREATE_BY": 1,
   "CREATE_DATETIME": "11/4/2019 3:52:24 PM",
   "UPDATE_BY": 1,
   "UPDATE_DATETIME": "11/4/2019 3:52:24 PM",
   "ACTIVEMAIN": "Master",
   "ACTIVE": "DCQ",
   "MENU_ICON": "",
   "MENU_ID": 23
 },
 {
   "TABLENAME": "M_MENU",
   "ID": 35,
   "MENU_NAME": "Average FX",
   "MENU_URL": "~/FxRate",
   "MENU_LEVEL": 2,
   "PARENT_MENU_ID": 3,
   "DESCRIPTION": "",
   "ROW_ORDER": 25,
   "IS_ACTIVE": 1,
   "CREATE_BY": 1,
   "CREATE_DATETIME": "6/25/2020 10:20:00 PM",
   "UPDATE_BY": null,
   "UPDATE_DATETIME": "",
   "ACTIVEMAIN": "Master",
   "ACTIVE": "FxRate",
   "MENU_ICON": "",
   "MENU_ID": 35
 },
 {
   "TABLENAME": "M_MENU",
   "ID": 26,
   "MENU_NAME": "Dubai Price",
   "MENU_URL": "~/ExchangeRate",
   "MENU_LEVEL": 2,
   "PARENT_MENU_ID": 3,
   "DESCRIPTION": "",
   "ROW_ORDER": 26,
   "IS_ACTIVE": 1,
   "CREATE_BY": 1,
   "CREATE_DATETIME": "8/21/2019 3:33:53 PM",
   "UPDATE_BY": 1,
   "UPDATE_DATETIME": "8/21/2019 3:33:53 PM",
   "ACTIVEMAIN": "Master",
   "ACTIVE": "ExchangeRate",
   "MENU_ICON": "",
   "MENU_ID": 26
 },
 {
   "TABLENAME": "M_MENU",
   "ID": 36,
   "MENU_NAME": "LNG Price",
   "MENU_URL": "~/LNGPrice",
   "MENU_LEVEL": 2,
   "PARENT_MENU_ID": 3,
   "DESCRIPTION": "",
   "ROW_ORDER": 26,
   "IS_ACTIVE": 1,
   "CREATE_BY": 1,
   "CREATE_DATETIME": "6/25/2020 10:20:04 PM",
   "UPDATE_BY": null,
   "UPDATE_DATETIME": "",
   "ACTIVEMAIN": "Transaction",
   "ACTIVE": "LNGPrice",
   "MENU_ICON": "",
   "MENU_ID": 36
 },
 {
   "TABLENAME": "M_MENU",
   "ID": 7,
   "MENU_NAME": "ผู้ใช้งาน",
   "MENU_URL": "~/User",
   "MENU_LEVEL": 2,
   "PARENT_MENU_ID": 11,
   "DESCRIPTION": "",
   "ROW_ORDER": 1,
   "IS_ACTIVE": 1,
   "CREATE_BY": 1,
   "CREATE_DATETIME": "11/4/2019 3:52:24 PM",
   "UPDATE_BY": 1,
   "UPDATE_DATETIME": "11/4/2019 3:52:24 PM",
   "ACTIVEMAIN": "System",
   "ACTIVE": "User",
   "MENU_ICON": "",
   "MENU_ID": 7
 },
 {
   "TABLENAME": "M_MENU",
   "ID": 44,
   "MENU_NAME": "อนุมัติคำขอเข้าใช้งานระบบ",
   "MENU_URL": "~/RegisterUser",
   "MENU_LEVEL": 2,
   "PARENT_MENU_ID": 11,
   "DESCRIPTION": "",
   "ROW_ORDER": 2,
   "IS_ACTIVE": 1,
   "CREATE_BY": 1,
   "CREATE_DATETIME": "6/18/2021 12:04:47 AM",
   "UPDATE_BY": 1,
   "UPDATE_DATETIME": "",
   "ACTIVEMAIN": "RegisterUser",
   "ACTIVE": "",
   "MENU_ICON": "",
   "MENU_ID": 44
 },
 {
   "TABLENAME": "M_MENU",
   "ID": 8,
   "MENU_NAME": "กลุ่มผู้ใช้งาน",
   "MENU_URL": "~/UserGroup",
   "MENU_LEVEL": 2,
   "PARENT_MENU_ID": 11,
   "DESCRIPTION": "",
   "ROW_ORDER": 3,
   "IS_ACTIVE": 1,
   "CREATE_BY": 1,
   "CREATE_DATETIME": "11/4/2019 3:52:24 PM",
   "UPDATE_BY": 1,
   "UPDATE_DATETIME": "11/4/2019 3:52:24 PM",
   "ACTIVEMAIN": "System",
   "ACTIVE": "UserGroup",
   "MENU_ICON": "",
   "MENU_ID": 8
 },
 {
   "TABLENAME": "M_MENU",
   "ID": 9,
   "MENU_NAME": "กำหนดสิทธิ์การใช้งาน",
   "MENU_URL": "~/Permissions",
   "MENU_LEVEL": 2,
   "PARENT_MENU_ID": 11,
   "DESCRIPTION": "",
   "ROW_ORDER": 15,
   "IS_ACTIVE": 1,
   "CREATE_BY": 1,
   "CREATE_DATETIME": "11/4/2019 3:52:25 PM",
   "UPDATE_BY": 1,
   "UPDATE_DATETIME": "11/4/2019 3:52:25 PM",
   "ACTIVEMAIN": "System",
   "ACTIVE": "Permissions",
   "MENU_ICON": "",
   "MENU_ID": 9
 },
 {
   "TABLENAME": "M_MENU",
   "ID": 10,
   "MENU_NAME": "Interface  SAP  Log",
   "MENU_URL": "~/Log",
   "MENU_LEVEL": 2,
   "PARENT_MENU_ID": 11,
   "DESCRIPTION": "",
   "ROW_ORDER": 16,
   "IS_ACTIVE": 1,
   "CREATE_BY": 1,
   "CREATE_DATETIME": "11/4/2019 3:52:25 PM",
   "UPDATE_BY": 1,
   "UPDATE_DATETIME": "11/4/2019 3:52:25 PM",
   "ACTIVEMAIN": "System",
   "ACTIVE": "Log",
   "MENU_ICON": "",
   "MENU_ID": 10
 },
 {
   "TABLENAME": "M_MENU",
   "ID": 12,
   "MENU_NAME": "ตั้งค่า Interface SAP",
   "MENU_URL": "~/InterfaceSAPSetting",
   "MENU_LEVEL": 2,
   "PARENT_MENU_ID": 11,
   "DESCRIPTION": "",
   "ROW_ORDER": 17,
   "IS_ACTIVE": 1,
   "CREATE_BY": 1,
   "CREATE_DATETIME": "11/4/2019 3:52:25 PM",
   "UPDATE_BY": 1,
   "UPDATE_DATETIME": "11/4/2019 3:52:25 PM",
   "ACTIVEMAIN": "System",
   "ACTIVE": "InterfaceSAPSetting",
   "MENU_ICON": "",
   "MENU_ID": 12
 },
 {
   "TABLENAME": "M_MENU",
   "ID": 16,
   "MENU_NAME": "Job",
   "MENU_URL": "~/Job",
   "MENU_LEVEL": 2,
   "PARENT_MENU_ID": 11,
   "DESCRIPTION": "",
   "ROW_ORDER": 18,
   "IS_ACTIVE": 1,
   "CREATE_BY": 1,
   "CREATE_DATETIME": "11/4/2019 3:52:25 PM",
   "UPDATE_BY": 1,
   "UPDATE_DATETIME": "11/4/2019 3:52:25 PM",
   "ACTIVEMAIN": "System",
   "ACTIVE": "Job",
   "MENU_ICON": "",
   "MENU_ID": 16
 },
 {
   "TABLENAME": "M_MENU",
   "ID": 18,
   "MENU_NAME": "Email Template",
   "MENU_URL": "~/EmailTemplate",
   "MENU_LEVEL": 2,
   "PARENT_MENU_ID": 11,
   "DESCRIPTION": "",
   "ROW_ORDER": 19,
   "IS_ACTIVE": 1,
   "CREATE_BY": 1,
   "CREATE_DATETIME": "11/4/2019 3:52:25 PM",
   "UPDATE_BY": 1,
   "UPDATE_DATETIME": "11/4/2019 3:52:25 PM",
   "ACTIVEMAIN": "System",
   "ACTIVE": "EmailTemplate",
   "MENU_ICON": "",
   "MENU_ID": 18
 },
 {
   "TABLENAME": "M_MENU",
   "ID": 19,
   "MENU_NAME": "Email List",
   "MENU_URL": "~/EmailList",
   "MENU_LEVEL": 2,
   "PARENT_MENU_ID": 11,
   "DESCRIPTION": "",
   "ROW_ORDER": 20,
   "IS_ACTIVE": 1,
   "CREATE_BY": 1,
   "CREATE_DATETIME": "11/4/2019 3:52:25 PM",
   "UPDATE_BY": 1,
   "UPDATE_DATETIME": "11/4/2019 3:52:25 PM",
   "ACTIVEMAIN": "System",
   "ACTIVE": "EmailList",
   "MENU_ICON": "",
   "MENU_ID": 19
 },
 {
   "TABLENAME": "M_MENU",
   "ID": 50,
   "MENU_NAME": "Auto Approve Config",
   "MENU_URL": "~/AutoApproveConfig",
   "MENU_LEVEL": 2,
   "PARENT_MENU_ID": 11,
   "DESCRIPTION": "",
   "ROW_ORDER": 21,
   "IS_ACTIVE": 1,
   "CREATE_BY": 1,
   "CREATE_DATETIME": "11/4/2019 3:52:25 PM",
   "UPDATE_BY": 1,
   "UPDATE_DATETIME": "11/4/2019 3:52:25 PM",
   "ACTIVEMAIN": "System",
   "ACTIVE": "AutoApproveConfig",
   "MENU_ICON": "",
   "MENU_ID": 50
 }
];
let nextId = 1003;

function createMockToken(expiresAt: string) {
  const header = { alg: "none", typ: "JWT" };
  const payload = { exp: Math.floor(Date.parse(expiresAt) / 1000) };

  const encode = (value: object) =>
    btoa(JSON.stringify(value))
      .replace(/\+/g, "-")
      .replace(/\//g, "_")
      .replace(/=+$/, "");

  return `${encode(header)}.${encode(payload)}.mock`;
}

export async function mockAuthenticate(
  payload: AuthPayload
): Promise<AuthSession> {
  const expiresAt = new Date(Date.now() + 60 * 60 * 1000).toISOString();//60 minutes
  //const expiresAt = new Date(Date.now() + 1 * 60 * 1000).toISOString();//1 minutes
  const [firstName, lastName = "User"] = payload.username.split(".");
  const menus = menu

  return {
    userId: `user-${payload.domain}-${payload.username}`,
    name: firstName || payload.username || "User",
    lastName,
    token: createMockToken(expiresAt),
    expiresAt,
    menus,
  };
}

export async function mockFetchUsers(): Promise<User[]> {
  return [...users];
}

export async function mockFetchUserById(id: string): Promise<User> {
  const user = users.find((item) => item.id === id);
  if (!user) {
    throw new Error("User not found");
  }
  return { ...user };
}

export async function mockCreateUser(payload: UserPayload): Promise<User> {
  const createdAt = now();
  const user: User = {
    id: `U-${nextId++}`,
    firstName: payload.firstName,
    lastName: payload.lastName,
    email: payload.email,
    phone: payload.phone,
    role: payload.role,
    status: payload.status ?? "active",
    createdAt,
    updatedAt: createdAt,
  };

  users = [user, ...users];
  return { ...user };
}

export async function mockUpdateUser(
  id: string,
  payload: UserPayload
): Promise<User> {
  const index = users.findIndex((item) => item.id === id);
  if (index === -1) {
    throw new Error("User not found");
  }

  const updated: User = {
    ...users[index],
    ...payload,
    updatedAt: now(),
  };

  users = users.map((item, idx) => (idx === index ? updated : item));
  return { ...updated };
}

export async function mockDeleteUser(id: string): Promise<void> {
  const index = users.findIndex((item) => item.id === id);
  if (index === -1) {
    throw new Error("User not found");
  }
  users = users.filter((item) => item.id !== id);
}
